export const usersActionTypes = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOG_OUT: "LOG_OUT",
  AUTH_FAILURE: "AUTH_FAILURE",
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
};
